import 'package:get/get.dart';

class YourClosetController extends GetxController {
  RxString isSelectedItem = 'Gloves'.obs;
  List<String> categoryNames = [
    'Wallets',
    'Shoes',
    'Topwear',
    'Innerwear',
    'Bottomwear',
    'Socks',
    'Loungewear\nand\nNightwear',
    'Belts',
    'Saree',
    'Bags',
    'Watches',
    'Flip Flops',
    'Sandal',
    'Jewellery',
    'Accessories',
    'Ties',
    'Eyewear',
    'Headwear',
    'Dress',
    'Mufflers',
    'Cufflinks',
    'Apparel Set',
    'Water Bottle',
    'Stoles',
    'Scarves',
    'Gloves',
    'Sports Accessories',
    'Umbrellas',
    'Perfumes',
    'Shoe Accessories'
  ];
  List<String> categoryIcons = [
    'asset/category_image/wallet.png',
    'asset/category_image/shoes.png',
    'asset/category_image/topwear.png',
    'asset/category_image/innerwear.png',
    'asset/category_image/bottomwear.png',
    'asset/category_image/socks.png',
    'asset/category_image/nightwear.png',
    'asset/category_image/belt.png',
    'asset/category_image/saree.png',
    'asset/category_image/bags.png',
    'asset/category_image/watch.png',
    'asset/category_image/flipflop.png',
    'asset/category_image/sandal.png',
    'asset/category_image/jewelry.png',
    'asset/category_image/accessories.png',
    'asset/category_image/ties.png',
    'asset/category_image/eyewear.png',
    'asset/category_image/headwear.png',
    'asset/category_image/dress.png',
    'asset/category_image/muffler.png',
    'asset/category_image/cufflinks.png',
    'asset/category_image/Apparel Set.png',
    'asset/category_image/plastic-bottle.png',
    'asset/category_image/stole.png',
    'asset/category_image/scraf.png',
    'asset/category_image/gloves.png',
    'asset/category_image/sports.png',
    'asset/category_image/umbrella.png',
    'asset/category_image/perfume.png',
    'asset/category_image/polish.png'
  ];
}
